export const routes = {
  home: '/',
  login: '/login',
  privacy: '/privacy',
  security: '/security',
  trust: '/trust',
  trustDocument: (slug: string) => `/trust/${slug}`,
  dashboard: '/dashboard',
  surveys: '/surveys',
  newSurvey: '/surveys/new',
  editSurvey: (surveyId: string) => `/surveys/${surveyId}/edit`,
  editSurveyPrivacy: (surveyId: string) => `/surveys/${surveyId}/edit#privacy`,
  profile: '/profile',
  resultsHome: '/results',
  results: (surveyId: string) => `/surveys/${surveyId}/results`,
  resultsPresentation: (surveyId: string) =>
    `/surveys/${surveyId}/results/present`,
  joinWorkspace: (token: string) => `/join/${token}`,
  respondent: (slug: string) => `/s/${slug}`,
};
